name: Register image
description: Build and register a production-ready image from a Dockerfile to a private registry.
branding:
  icon: box
  color: blue

inputs:
  image:
    description: Image name
    required: true
    type: string
  version:
    description: Image version
    required: true
    type: string
  password:
    description: GitHub token
    required: true
    type: string
  registry:
    description: Host registry
    required: false
    type: string
    default: ghcr.io
  platforms:
    description: Specify which platform to build the image for
    required: false
    type: string
    default: linux/amd64

runs:
  using: composite
  steps:
    - name: Check out into the repository
      uses: actions/checkout@v4
    - name: Log into the host registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}          
        password: ${{ inputs.password }}
    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v3
    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push the image to the host registry
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        target: production
        platforms: ${{ inputs.platforms }}
        tags: |
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}:latest
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image }}:${{ inputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
